### ISSUE TITLE
Action Originate Returns -1

### ISSUE THREAD

**Issue by anandeshwar** [InterLinked1/cami#8]
Hi there,

I have used the cami library to originate a call using originate api function which comes with the library.
However, after originate action the end user being dialed correctly, but, the action response result is -1.
Also, i am interested in the response information to know the details of the call originate reponse to get
the details such as Channel information etc. 
 
Right now the response retuns NULL.

Let me know whether you have encountered the same issue and would like to fix these issues in future 
release.

Best Regards,
Anand

**Comment by InterLinked1** [comment]
Sorry for the delay and thanks for reporting this issue! It's in my queue to look at but I'm a bit backed up at the moment so apologies for the delay. It's in our internal issue tracker and I hope to take a look at it soon!

**Comment by InterLinked1** [comment]
> Hi there,
> 
> I have used the cami library to originate a call using originate api function which comes with the library. However, after originate action the end user being dialed correctly, but, the action response result is -1. Also, i am interested in the response information to know the details of the call originate reponse to get the details such as Channel information etc.
> 
> Right now the response retuns NULL.
> 
> Let me know whether you have encountered the same issue and would like to fix these issues in future release.

I've taken a look at this but I think a few more details are needed in order to get the entire picture. Could you provide a simple code snippet or list of functions which demonstrates both of the things you're talking about?

My initial thought is if you are using ami_action_originate_exten, it won't return any additional information, just 0 or 1 to indicate success/failure. You could get that information by using ami_action directly, but I can see how it would be convenient to have an "inbetween" function that isn't that low-level while still returning the full response.

**Comment by InterLinked1** [comment]
> Hi there,
> 
> I have used the cami library to originate a call using originate api function which comes with the library. However, after originate action the end user being dialed correctly, but, the action response result is -1. Also, i am interested in the response information to know the details of the call originate reponse to get the details such as Channel information etc.
> 
> Right now the response retuns NULL.
> 
> Let me know whether you have encountered the same issue and would like to fix these issues in future release.

Since there's not enough information here to reproduce, and there's been no response, I'm closing this issue. Feel free to reopen if this is still an issue.
